RegistrationFormApp/RegistrationFormWeb/Models/RegistrationFormModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace RegistrationFormWeb.Models
{
    public class RegistrationFormModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string StateName { get; set; }
        public string CityName { get; set; }

    }
    public class RegistrationFormInsertModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public int StateId { get; set; }
        public int CityId { get; set; }
    }

    public class StateModel
    {
        public int Id { get; set; }
        public string StateName { get; set; }
    }

    public class CityModel
    {
        public int Id { get; set; }
        public int StateId { get; set; }
        public string CityName { get; set; }
    }
}

RegistrationFormApp/RegistrationFormWeb/Controllers/RegisterFormController.cs
using RegistrationFormWeb.Models;
using RegistrationFormWeb.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RegistrationFormWeb.Controllers
{
    public class RegisterFormController : Controller
    {
        RegisterDAL registerDAL=new RegisterDAL();
        public ActionResult Index()
        {
            return View();
        }
       
        [HttpGet]
        public ActionResult GetAllDetails()
        {
            List<RegistrationFormModel> allDetails = registerDAL.GetAllDetails();
            return Json(allDetails,JsonRequestBehavior.AllowGet);
        }
        
        [HttpGet]
        public ActionResult GetAllState()
        {
            List<StateModel> stateList = registerDAL.GetAllStates();
            return Json(stateList, JsonRequestBehavior.AllowGet);
        }
       
        [HttpGet]
        public ActionResult GetAllCities(int stateId)
        {
            List<CityModel> cityList = registerDAL.GetAllCities(stateId);
            return Json(cityList, JsonRequestBehavior.AllowGet);
        }
       
        [HttpPost]
        public ActionResult DeleteDetail(int id)
        {
            bool deleted = registerDAL.Deletedetail(id);
            return Json(deleted, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult GetAllDetailById(int id)
        {
            RegistrationFormInsertModel detailById = registerDAL.GetDetailsbyId(id);
            return Json(detailById, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult InsertUpdateDetails(RegistrationFormInsertModel obj)
        {
            bool isInserted = registerDAL.InsertUpdateDetails(obj);
            return Json(isInserted, JsonRequestBehavior.AllowGet);
        }
    }

}

RegistrationFormApp/RegistrationFormWeb/Views/RegisterForm/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <button type="button" class="btn btn-primary" id="showModal" onclick="clearTextBox();">Add New Detail</button><br /><br />
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>
                    ID
                </th>
                <th>
                    Name
                </th>
                <th>
                    Email
                </th>
                <th>
                    Phone
                </th>
                <th>
                    Address
                </th>
                <th>
                    State
                </th>
                <th>
                    Country
                </th>
                <th>
                    Action
                </th>
            </tr>
        </thead>
        <tbody class="tbody">
        </tbody>
    </table>
</div>
<div class="modal fade" id="registrationFormModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-bs-dismiss="modal">&times;</button>
                <h4 class="modal-title" id="myModalLabel">Add Detail</h4>
            </div>
            <div class="modal-body">
                <form>
                    <input type="hidden" id="hdnID" />
                    <div class="form-group">
                        <label for="Name">Name</label>
                        <input type="text" class="form-control" id="Name" placeholder="Name" />
                    </div>
                    <div class="form-group">
                        <label for="Email">Email</label>
                        <input type="text" class="form-control" id="Email" placeholder="Email" title="Invalid email address"/>
                    </div>
                    <div class="form-group">
                        <label for="Phone">Phone</label>
                        <input type="text" class="form-control" maxlength="10" pattern="[1-9]{1}[0-9]{9}" id="Phone" placeholder="Phone"
                               title="Phone number with 6-9 and remaing 9 digit with 0-9" />
                    </div>
                    <div class="form-group">
                        <label for="Address">Address</label>
                        <input type="text" class="form-control" id="Address" placeholder="Address" />
                    </div>
                    <div class="form-group">
                        <label for="State">State</label>
                        <select name="state-dropdown" id="state-dropdown" class="form-control"></select>
                    </div>
                    <div class="form-group">
                        <label for="City">City</label>
                        <select name="city-dropdown" id="city-dropdown" class="form-control"></select>
                    </div>
                    <div class="form-group">
                        <label class="form-label">
                            Agree?
                        </label>
                        <input type="checkbox" id="agree"/>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" id="btnSubmit" onclick="return InsertUpdateDetail();">Submit</button>
                <button type="button" class="btn btn-default" data-bs-dismiss="modal">Cancel</button>
            </div>
        </div>
    </div>
</div>
@section scripts{
    <script src="~/Scripts/RegistrationForm.js" type="text/javascript"></script>
}

RegistrationFormApp/RegistrationFormWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="#" />
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/toastr.min.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                @Html.ActionLink("Registration Form", "Index", "RegisterForm", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>

    <script src="~/Scripts/jquery-3.6.3.min.js" type="text/javascript"></script>
    <script src="~/Scripts/jquery.validate.min.js" type="text/javascript"></script>
    <script src="~/Scripts/bootstrap.min.js" type="text/javascript"></script>
    <script src="~/Scripts/toastr.min.js" type="text/javascript"></script>
    @RenderSection("scripts", required: false)
</body>
</html>